package com.liubs.shadowrpc.research.entity;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity/Person.proto

// Protobuf Java Version: 3.25.1
public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 基本数据类型
     * </pre>
     *
     * <code>uint32 sex = 1;</code>
     * @return The sex.
     */
    int getSex();

    /**
     * <pre>
     * short 映射为 uint32
     * </pre>
     *
     * <code>uint32 like = 2;</code>
     * @return The like.
     */
    int getLike();

    /**
     * <pre>
     * char 映射为 uint32
     * </pre>
     *
     * <code>uint32 hair = 3;</code>
     * @return The hair.
     */
    int getHair();

    /**
     * <code>bool isMan = 4;</code>
     * @return The isMan.
     */
    boolean getIsMan();

    /**
     * <code>int32 age = 5;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>double height = 6;</code>
     * @return The height.
     */
    double getHeight();

    /**
     * <code>float weight = 7;</code>
     * @return The weight.
     */
    float getWeight();

    /**
     * <code>int64 money = 8;</code>
     * @return The money.
     */
    long getMoney();

    /**
     * <pre>
     * 字符串
     * </pre>
     *
     * <code>string name = 9;</code>
     * @return The name.
     */
    String getName();
    /**
     * <pre>
     * 字符串
     * </pre>
     *
     * <code>string name = 9;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonOuterClass.internal_static_Person_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonOuterClass.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.class, Builder.class);
    }

    public static final int SEX_FIELD_NUMBER = 1;
    private int sex_ = 0;
    /**
     * <pre>
     * 基本数据类型
     * </pre>
     *
     * <code>uint32 sex = 1;</code>
     * @return The sex.
     */
    @Override
    public int getSex() {
      return sex_;
    }

    public static final int LIKE_FIELD_NUMBER = 2;
    private int like_ = 0;
    /**
     * <pre>
     * short 映射为 uint32
     * </pre>
     *
     * <code>uint32 like = 2;</code>
     * @return The like.
     */
    @Override
    public int getLike() {
      return like_;
    }

    public static final int HAIR_FIELD_NUMBER = 3;
    private int hair_ = 0;
    /**
     * <pre>
     * char 映射为 uint32
     * </pre>
     *
     * <code>uint32 hair = 3;</code>
     * @return The hair.
     */
    @Override
    public int getHair() {
      return hair_;
    }

    public static final int ISMAN_FIELD_NUMBER = 4;
    private boolean isMan_ = false;
    /**
     * <code>bool isMan = 4;</code>
     * @return The isMan.
     */
    @Override
    public boolean getIsMan() {
      return isMan_;
    }

    public static final int AGE_FIELD_NUMBER = 5;
    private int age_ = 0;
    /**
     * <code>int32 age = 5;</code>
     * @return The age.
     */
    @Override
    public int getAge() {
      return age_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private double height_ = 0D;
    /**
     * <code>double height = 6;</code>
     * @return The height.
     */
    @Override
    public double getHeight() {
      return height_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 7;
    private float weight_ = 0F;
    /**
     * <code>float weight = 7;</code>
     * @return The weight.
     */
    @Override
    public float getWeight() {
      return weight_;
    }

    public static final int MONEY_FIELD_NUMBER = 8;
    private long money_ = 0L;
    /**
     * <code>int64 money = 8;</code>
     * @return The money.
     */
    @Override
    public long getMoney() {
      return money_;
    }

    public static final int NAME_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile Object name_ = "";
    /**
     * <pre>
     * 字符串
     * </pre>
     *
     * <code>string name = 9;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 字符串
     * </pre>
     *
     * <code>string name = 9;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sex_ != 0) {
        output.writeUInt32(1, sex_);
      }
      if (like_ != 0) {
        output.writeUInt32(2, like_);
      }
      if (hair_ != 0) {
        output.writeUInt32(3, hair_);
      }
      if (isMan_ != false) {
        output.writeBool(4, isMan_);
      }
      if (age_ != 0) {
        output.writeInt32(5, age_);
      }
      if (Double.doubleToRawLongBits(height_) != 0) {
        output.writeDouble(6, height_);
      }
      if (Float.floatToRawIntBits(weight_) != 0) {
        output.writeFloat(7, weight_);
      }
      if (money_ != 0L) {
        output.writeInt64(8, money_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, sex_);
      }
      if (like_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, like_);
      }
      if (hair_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, hair_);
      }
      if (isMan_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isMan_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, age_);
      }
      if (Double.doubleToRawLongBits(height_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, height_);
      }
      if (Float.floatToRawIntBits(weight_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, weight_);
      }
      if (money_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, money_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Person)) {
        return super.equals(obj);
      }
      Person other = (Person) obj;

      if (getSex()
          != other.getSex()) return false;
      if (getLike()
          != other.getLike()) return false;
      if (getHair()
          != other.getHair()) return false;
      if (getIsMan()
          != other.getIsMan()) return false;
      if (getAge()
          != other.getAge()) return false;
      if (Double.doubleToLongBits(getHeight())
          != Double.doubleToLongBits(
              other.getHeight())) return false;
      if (Float.floatToIntBits(getWeight())
          != Float.floatToIntBits(
              other.getWeight())) return false;
      if (getMoney()
          != other.getMoney()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      hash = (37 * hash) + LIKE_FIELD_NUMBER;
      hash = (53 * hash) + getLike();
      hash = (37 * hash) + HAIR_FIELD_NUMBER;
      hash = (53 * hash) + getHair();
      hash = (37 * hash) + ISMAN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsMan());
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getHeight()));
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getWeight());
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMoney());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonOuterClass.internal_static_Person_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonOuterClass.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.class, Builder.class);
      }

      // Construct using PersonOuterClass.Person.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sex_ = 0;
        like_ = 0;
        hair_ = 0;
        isMan_ = false;
        age_ = 0;
        height_ = 0D;
        weight_ = 0F;
        money_ = 0L;
        name_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonOuterClass.internal_static_Person_descriptor;
      }

      @Override
      public Person getDefaultInstanceForType() {
        return Person.getDefaultInstance();
      }

      @Override
      public Person build() {
        Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Person buildPartial() {
        Person result = new Person(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Person result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sex_ = sex_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.like_ = like_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.hair_ = hair_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.isMan_ = isMan_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.age_ = age_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.height_ = height_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.weight_ = weight_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.money_ = money_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.name_ = name_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person) {
          return mergeFrom((Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person other) {
        if (other == Person.getDefaultInstance()) return this;
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        if (other.getLike() != 0) {
          setLike(other.getLike());
        }
        if (other.getHair() != 0) {
          setHair(other.getHair());
        }
        if (other.getIsMan() != false) {
          setIsMan(other.getIsMan());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getHeight() != 0D) {
          setHeight(other.getHeight());
        }
        if (other.getWeight() != 0F) {
          setWeight(other.getWeight());
        }
        if (other.getMoney() != 0L) {
          setMoney(other.getMoney());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                sex_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                like_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                hair_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                isMan_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 49: {
                height_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              case 61: {
                weight_ = input.readFloat();
                bitField0_ |= 0x00000040;
                break;
              } // case 61
              case 64: {
                money_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 74: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int sex_ ;
      /**
       * <pre>
       * 基本数据类型
       * </pre>
       *
       * <code>uint32 sex = 1;</code>
       * @return The sex.
       */
      @Override
      public int getSex() {
        return sex_;
      }
      /**
       * <pre>
       * 基本数据类型
       * </pre>
       *
       * <code>uint32 sex = 1;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(int value) {

        sex_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 基本数据类型
       * </pre>
       *
       * <code>uint32 sex = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sex_ = 0;
        onChanged();
        return this;
      }

      private int like_ ;
      /**
       * <pre>
       * short 映射为 uint32
       * </pre>
       *
       * <code>uint32 like = 2;</code>
       * @return The like.
       */
      @Override
      public int getLike() {
        return like_;
      }
      /**
       * <pre>
       * short 映射为 uint32
       * </pre>
       *
       * <code>uint32 like = 2;</code>
       * @param value The like to set.
       * @return This builder for chaining.
       */
      public Builder setLike(int value) {

        like_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * short 映射为 uint32
       * </pre>
       *
       * <code>uint32 like = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLike() {
        bitField0_ = (bitField0_ & ~0x00000002);
        like_ = 0;
        onChanged();
        return this;
      }

      private int hair_ ;
      /**
       * <pre>
       * char 映射为 uint32
       * </pre>
       *
       * <code>uint32 hair = 3;</code>
       * @return The hair.
       */
      @Override
      public int getHair() {
        return hair_;
      }
      /**
       * <pre>
       * char 映射为 uint32
       * </pre>
       *
       * <code>uint32 hair = 3;</code>
       * @param value The hair to set.
       * @return This builder for chaining.
       */
      public Builder setHair(int value) {

        hair_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * char 映射为 uint32
       * </pre>
       *
       * <code>uint32 hair = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHair() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hair_ = 0;
        onChanged();
        return this;
      }

      private boolean isMan_ ;
      /**
       * <code>bool isMan = 4;</code>
       * @return The isMan.
       */
      @Override
      public boolean getIsMan() {
        return isMan_;
      }
      /**
       * <code>bool isMan = 4;</code>
       * @param value The isMan to set.
       * @return This builder for chaining.
       */
      public Builder setIsMan(boolean value) {

        isMan_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool isMan = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsMan() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isMan_ = false;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 5;</code>
       * @return The age.
       */
      @Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 5;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000010);
        age_ = 0;
        onChanged();
        return this;
      }

      private double height_ ;
      /**
       * <code>double height = 6;</code>
       * @return The height.
       */
      @Override
      public double getHeight() {
        return height_;
      }
      /**
       * <code>double height = 6;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(double value) {

        height_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double height = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000020);
        height_ = 0D;
        onChanged();
        return this;
      }

      private float weight_ ;
      /**
       * <code>float weight = 7;</code>
       * @return The weight.
       */
      @Override
      public float getWeight() {
        return weight_;
      }
      /**
       * <code>float weight = 7;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(float value) {

        weight_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>float weight = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000040);
        weight_ = 0F;
        onChanged();
        return this;
      }

      private long money_ ;
      /**
       * <code>int64 money = 8;</code>
       * @return The money.
       */
      @Override
      public long getMoney() {
        return money_;
      }
      /**
       * <code>int64 money = 8;</code>
       * @param value The money to set.
       * @return This builder for chaining.
       */
      public Builder setMoney(long value) {

        money_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int64 money = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoney() {
        bitField0_ = (bitField0_ & ~0x00000080);
        money_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       * 字符串
       * </pre>
       *
       * <code>string name = 9;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 字符串
       * </pre>
       *
       * <code>string name = 9;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 字符串
       * </pre>
       *
       * <code>string name = 9;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字符串
       * </pre>
       *
       * <code>string name = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字符串
       * </pre>
       *
       * <code>string name = 9;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person();
    }

    public static Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @Override
    public Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023entity/Person.proto\"\212\001\n\006Person\022\013\n\003sex\030" +
      "\001 \001(\r\022\014\n\004like\030\002 \001(\r\022\014\n\004hair\030\003 \001(\r\022\r\n\005isM" +
      "an\030\004 \001(\010\022\013\n\003age\030\005 \001(\005\022\016\n\006height\030\006 \001(\001\022\016\n" +
      "\006weight\030\007 \001(\002\022\r\n\005money\030\010 \001(\003\022\014\n\004name\030\t \001" +
      "(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new String[] { "Sex", "Like", "Hair", "IsMan", "Age", "Height", "Weight", "Money", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
