// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimplePersonProto.proto

// Protobuf Java Version: 3.25.1
package com.liubs.shadowrpc.research.entity;

public final class SimplePersonProto {
  private SimplePersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimplePersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.liubs.shadowrpc.research.entity.SimplePerson)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>double height = 2;</code>
     * @return The height.
     */
    double getHeight();

    /**
     * <code>float weight = 3;</code>
     * @return The weight.
     */
    float getWeight();

    /**
     * <code>int64 money = 4;</code>
     * @return The money.
     */
    long getMoney();

    /**
     * <code>string name = 5;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.liubs.shadowrpc.research.entity.SimplePerson}
   */
  public static final class SimplePerson extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.liubs.shadowrpc.research.entity.SimplePerson)
      SimplePersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimplePerson.newBuilder() to construct.
    private SimplePerson(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimplePerson() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimplePerson();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SimplePerson.class, Builder.class);
    }

    public static final int AGE_FIELD_NUMBER = 1;
    private int age_ = 0;
    /**
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    @Override
    public int getAge() {
      return age_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private double height_ = 0D;
    /**
     * <code>double height = 2;</code>
     * @return The height.
     */
    @Override
    public double getHeight() {
      return height_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 3;
    private float weight_ = 0F;
    /**
     * <code>float weight = 3;</code>
     * @return The weight.
     */
    @Override
    public float getWeight() {
      return weight_;
    }

    public static final int MONEY_FIELD_NUMBER = 4;
    private long money_ = 0L;
    /**
     * <code>int64 money = 4;</code>
     * @return The money.
     */
    @Override
    public long getMoney() {
      return money_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object name_ = "";
    /**
     * <code>string name = 5;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (age_ != 0) {
        output.writeInt32(1, age_);
      }
      if (Double.doubleToRawLongBits(height_) != 0) {
        output.writeDouble(2, height_);
      }
      if (Float.floatToRawIntBits(weight_) != 0) {
        output.writeFloat(3, weight_);
      }
      if (money_ != 0L) {
        output.writeInt64(4, money_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (Double.doubleToRawLongBits(height_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, height_);
      }
      if (Float.floatToRawIntBits(weight_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, weight_);
      }
      if (money_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, money_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SimplePerson)) {
        return super.equals(obj);
      }
      SimplePerson other = (SimplePerson) obj;

      if (getAge()
          != other.getAge()) return false;
      if (Double.doubleToLongBits(getHeight())
          != Double.doubleToLongBits(
              other.getHeight())) return false;
      if (Float.floatToIntBits(getWeight())
          != Float.floatToIntBits(
              other.getWeight())) return false;
      if (getMoney()
          != other.getMoney()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getHeight()));
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getWeight());
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMoney());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SimplePerson parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimplePerson parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimplePerson parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimplePerson parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimplePerson parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimplePerson parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimplePerson parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimplePerson parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SimplePerson parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SimplePerson parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SimplePerson parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimplePerson parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SimplePerson prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.liubs.shadowrpc.research.entity.SimplePerson}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.liubs.shadowrpc.research.entity.SimplePerson)
        SimplePersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SimplePerson.class, Builder.class);
      }

      // Construct using com.liubs.shadowrpc.research.entity.SimplePersonProto.SimplePerson.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        age_ = 0;
        height_ = 0D;
        weight_ = 0F;
        money_ = 0L;
        name_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_descriptor;
      }

      @Override
      public SimplePerson getDefaultInstanceForType() {
        return SimplePerson.getDefaultInstance();
      }

      @Override
      public SimplePerson build() {
        SimplePerson result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SimplePerson buildPartial() {
        SimplePerson result = new SimplePerson(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SimplePerson result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.age_ = age_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.height_ = height_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.weight_ = weight_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.money_ = money_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.name_ = name_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SimplePerson) {
          return mergeFrom((SimplePerson)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SimplePerson other) {
        if (other == SimplePerson.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getHeight() != 0D) {
          setHeight(other.getHeight());
        }
        if (other.getWeight() != 0F) {
          setWeight(other.getWeight());
        }
        if (other.getMoney() != 0L) {
          setMoney(other.getMoney());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                height_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 29: {
                weight_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 32: {
                money_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int age_ ;
      /**
       * <code>int32 age = 1;</code>
       * @return The age.
       */
      @Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 1;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        onChanged();
        return this;
      }

      private double height_ ;
      /**
       * <code>double height = 2;</code>
       * @return The height.
       */
      @Override
      public double getHeight() {
        return height_;
      }
      /**
       * <code>double height = 2;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(double value) {

        height_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double height = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        height_ = 0D;
        onChanged();
        return this;
      }

      private float weight_ ;
      /**
       * <code>float weight = 3;</code>
       * @return The weight.
       */
      @Override
      public float getWeight() {
        return weight_;
      }
      /**
       * <code>float weight = 3;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(float value) {

        weight_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float weight = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        weight_ = 0F;
        onChanged();
        return this;
      }

      private long money_ ;
      /**
       * <code>int64 money = 4;</code>
       * @return The money.
       */
      @Override
      public long getMoney() {
        return money_;
      }
      /**
       * <code>int64 money = 4;</code>
       * @param value The money to set.
       * @return This builder for chaining.
       */
      public Builder setMoney(long value) {

        money_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 money = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoney() {
        bitField0_ = (bitField0_ & ~0x00000008);
        money_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 5;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.liubs.shadowrpc.research.entity.SimplePerson)
    }

    // @@protoc_insertion_point(class_scope:com.liubs.shadowrpc.research.entity.SimplePerson)
    private static final SimplePerson DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SimplePerson();
    }

    public static SimplePerson getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimplePerson>
        PARSER = new com.google.protobuf.AbstractParser<SimplePerson>() {
      @Override
      public SimplePerson parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SimplePerson> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SimplePerson> getParserForType() {
      return PARSER;
    }

    @Override
    public SimplePerson getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimplePersonsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.liubs.shadowrpc.research.entity.SimplePersons)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    java.util.List<SimplePerson>
        getItemsList();
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    SimplePerson getItems(int index);
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    java.util.List<? extends SimplePersonOrBuilder>
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    SimplePersonOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.liubs.shadowrpc.research.entity.SimplePersons}
   */
  public static final class SimplePersons extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.liubs.shadowrpc.research.entity.SimplePersons)
      SimplePersonsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimplePersons.newBuilder() to construct.
    private SimplePersons(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimplePersons() {
      items_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimplePersons();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SimplePersons.class, Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<SimplePerson> items_;
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    @Override
    public java.util.List<SimplePerson> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    @Override
    public java.util.List<? extends SimplePersonOrBuilder>
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    @Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    @Override
    public SimplePerson getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
     */
    @Override
    public SimplePersonOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SimplePersons)) {
        return super.equals(obj);
      }
      SimplePersons other = (SimplePersons) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SimplePersons parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimplePersons parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimplePersons parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimplePersons parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimplePersons parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimplePersons parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimplePersons parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimplePersons parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SimplePersons parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SimplePersons parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SimplePersons parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimplePersons parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SimplePersons prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.liubs.shadowrpc.research.entity.SimplePersons}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.liubs.shadowrpc.research.entity.SimplePersons)
        SimplePersonsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SimplePersons.class, Builder.class);
      }

      // Construct using com.liubs.shadowrpc.research.entity.SimplePersonProto.SimplePersons.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SimplePersonProto.internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_descriptor;
      }

      @Override
      public SimplePersons getDefaultInstanceForType() {
        return SimplePersons.getDefaultInstance();
      }

      @Override
      public SimplePersons build() {
        SimplePersons result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SimplePersons buildPartial() {
        SimplePersons result = new SimplePersons(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(SimplePersons result) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
      }

      private void buildPartial0(SimplePersons result) {
        int from_bitField0_ = bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SimplePersons) {
          return mergeFrom((SimplePersons)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SimplePersons other) {
        if (other == SimplePersons.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                SimplePerson m =
                    input.readMessage(
                        SimplePerson.parser(),
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<SimplePerson> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<SimplePerson>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          SimplePerson, SimplePerson.Builder, SimplePersonOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public java.util.List<SimplePerson> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public SimplePerson getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder setItems(
          int index, SimplePerson value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder setItems(
          int index, SimplePerson.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder addItems(SimplePerson value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder addItems(
          int index, SimplePerson value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder addItems(
          SimplePerson.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder addItems(
          int index, SimplePerson.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder addAllItems(
          Iterable<? extends SimplePerson> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public SimplePerson.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public SimplePersonOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public java.util.List<? extends SimplePersonOrBuilder>
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public SimplePerson.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            SimplePerson.getDefaultInstance());
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public SimplePerson.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, SimplePerson.getDefaultInstance());
      }
      /**
       * <code>repeated .com.liubs.shadowrpc.research.entity.SimplePerson items = 1;</code>
       */
      public java.util.List<SimplePerson.Builder>
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          SimplePerson, SimplePerson.Builder, SimplePersonOrBuilder>
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              SimplePerson, SimplePerson.Builder, SimplePersonOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.liubs.shadowrpc.research.entity.SimplePersons)
    }

    // @@protoc_insertion_point(class_scope:com.liubs.shadowrpc.research.entity.SimplePersons)
    private static final SimplePersons DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SimplePersons();
    }

    public static SimplePersons getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimplePersons>
        PARSER = new com.google.protobuf.AbstractParser<SimplePersons>() {
      @Override
      public SimplePersons parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SimplePersons> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SimplePersons> getParserForType() {
      return PARSER;
    }

    @Override
    public SimplePersons getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027SimplePersonProto.proto\022#com.liubs.sha" +
      "dowrpc.research.entity\"X\n\014SimplePerson\022\013" +
      "\n\003age\030\001 \001(\005\022\016\n\006height\030\002 \001(\001\022\016\n\006weight\030\003 " +
      "\001(\002\022\r\n\005money\030\004 \001(\003\022\014\n\004name\030\005 \001(\t\"Q\n\rSimp" +
      "lePersons\022@\n\005items\030\001 \003(\01321.com.liubs.sha" +
      "dowrpc.research.entity.SimplePersonb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liubs_shadowrpc_research_entity_SimplePerson_descriptor,
        new String[] { "Age", "Height", "Weight", "Money", "Name", });
    internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liubs_shadowrpc_research_entity_SimplePersons_descriptor,
        new String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
