// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

// Protobuf Java Version: 3.25.1
package com.liubs.shadowrpc.protocol.entity;

public final class ShadowRPCRequestProto {
  private ShadowRPCRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShadowRPCRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.liubs.shadowrpc.protocol.entity.ShadowRPCRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string traceId = 1;</code>
     * @return The traceId.
     */
    java.lang.String getTraceId();
    /**
     * <code>string traceId = 1;</code>
     * @return The bytes for traceId.
     */
    com.google.protobuf.ByteString
        getTraceIdBytes();

    /**
     * <code>string serviceName = 2;</code>
     * @return The serviceName.
     */
    java.lang.String getServiceName();
    /**
     * <code>string serviceName = 2;</code>
     * @return The bytes for serviceName.
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>string methodName = 3;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 3;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <pre>
     *参数类名
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @return A list containing the paramTypes.
     */
    java.util.List<java.lang.String>
        getParamTypesList();
    /**
     * <pre>
     *参数类名
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @return The count of paramTypes.
     */
    int getParamTypesCount();
    /**
     * <pre>
     *参数类名
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    java.lang.String getParamTypes(int index);
    /**
     * <pre>
     *参数类名
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParamTypesBytes(int index);

    /**
     * <pre>
     *bytes类型充当参数
     * </pre>
     *
     * <code>repeated bytes params = 5;</code>
     * @return A list containing the params.
     */
    java.util.List<com.google.protobuf.ByteString> getParamsList();
    /**
     * <pre>
     *bytes类型充当参数
     * </pre>
     *
     * <code>repeated bytes params = 5;</code>
     * @return The count of params.
     */
    int getParamsCount();
    /**
     * <pre>
     *bytes类型充当参数
     * </pre>
     *
     * <code>repeated bytes params = 5;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    com.google.protobuf.ByteString getParams(int index);
  }
  /**
   * Protobuf type {@code com.liubs.shadowrpc.protocol.entity.ShadowRPCRequest}
   */
  public static final class ShadowRPCRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.liubs.shadowrpc.protocol.entity.ShadowRPCRequest)
      ShadowRPCRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShadowRPCRequest.newBuilder() to construct.
    private ShadowRPCRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShadowRPCRequest() {
      traceId_ = "";
      serviceName_ = "";
      methodName_ = "";
      paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      params_ = emptyList(com.google.protobuf.ByteString.class);
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShadowRPCRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest.class, com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest.Builder.class);
    }

    public static final int TRACEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object traceId_ = "";
    /**
     * <code>string traceId = 1;</code>
     * @return The traceId.
     */
    @java.lang.Override
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      }
    }
    /**
     * <code>string traceId = 1;</code>
     * @return The bytes for traceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICENAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serviceName_ = "";
    /**
     * <code>string serviceName = 2;</code>
     * @return The serviceName.
     */
    @java.lang.Override
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceName = 2;</code>
     * @return The bytes for serviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object methodName_ = "";
    /**
     * <code>string methodName = 3;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string methodName = 3;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMTYPES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList paramTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     *参数类名
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @return A list containing the paramTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParamTypesList() {
      return paramTypes_;
    }
    /**
     * <pre>
     *参数类名
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @return The count of paramTypes.
     */
    public int getParamTypesCount() {
      return paramTypes_.size();
    }
    /**
     * <pre>
     *参数类名
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    public java.lang.String getParamTypes(int index) {
      return paramTypes_.get(index);
    }
    /**
     * <pre>
     *参数类名
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParamTypesBytes(int index) {
      return paramTypes_.getByteString(index);
    }

    public static final int PARAMS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> params_ =
        emptyList(com.google.protobuf.ByteString.class);
    /**
     * <pre>
     *bytes类型充当参数
     * </pre>
     *
     * <code>repeated bytes params = 5;</code>
     * @return A list containing the params.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getParamsList() {
      return params_;
    }
    /**
     * <pre>
     *bytes类型充当参数
     * </pre>
     *
     * <code>repeated bytes params = 5;</code>
     * @return The count of params.
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <pre>
     *bytes类型充当参数
     * </pre>
     *
     * <code>repeated bytes params = 5;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    public com.google.protobuf.ByteString getParams(int index) {
      return params_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
      }
      for (int i = 0; i < paramTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, paramTypes_.getRaw(i));
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeBytes(5, params_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(paramTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamTypesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(params_.get(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest)) {
        return super.equals(obj);
      }
      com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest other = (com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest) obj;

      if (!getTraceId()
          .equals(other.getTraceId())) return false;
      if (!getServiceName()
          .equals(other.getServiceName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParamTypesList()
          .equals(other.getParamTypesList())) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceId().hashCode();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParamTypesCount() > 0) {
        hash = (37 * hash) + PARAMTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParamTypesList().hashCode();
      }
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.liubs.shadowrpc.protocol.entity.ShadowRPCRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.liubs.shadowrpc.protocol.entity.ShadowRPCRequest)
        com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest.class, com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest.Builder.class);
      }

      // Construct using com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        traceId_ = "";
        serviceName_ = "";
        methodName_ = "";
        paramTypes_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        params_ = emptyList(com.google.protobuf.ByteString.class);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_descriptor;
      }

      @java.lang.Override
      public com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest getDefaultInstanceForType() {
        return com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest build() {
        com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest buildPartial() {
        com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest result = new com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.traceId_ = traceId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serviceName_ = serviceName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.methodName_ = methodName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          paramTypes_.makeImmutable();
          result.paramTypes_ = paramTypes_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          params_.makeImmutable();
          result.params_ = params_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest) {
          return mergeFrom((com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest other) {
        if (other == com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest.getDefaultInstance()) return this;
        if (!other.getTraceId().isEmpty()) {
          traceId_ = other.traceId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.paramTypes_.isEmpty()) {
          if (paramTypes_.isEmpty()) {
            paramTypes_ = other.paramTypes_;
            bitField0_ |= 0x00000008;
          } else {
            ensureParamTypesIsMutable();
            paramTypes_.addAll(other.paramTypes_);
          }
          onChanged();
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            params_.makeImmutable();
            bitField0_ |= 0x00000010;
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                traceId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                serviceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                methodName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureParamTypesIsMutable();
                paramTypes_.add(s);
                break;
              } // case 34
              case 42: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureParamsIsMutable();
                params_.add(v);
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object traceId_ = "";
      /**
       * <code>string traceId = 1;</code>
       * @return The traceId.
       */
      public java.lang.String getTraceId() {
        java.lang.Object ref = traceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          traceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string traceId = 1;</code>
       * @return The bytes for traceId.
       */
      public com.google.protobuf.ByteString
          getTraceIdBytes() {
        java.lang.Object ref = traceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string traceId = 1;</code>
       * @param value The traceId to set.
       * @return This builder for chaining.
       */
      public Builder setTraceId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        traceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string traceId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTraceId() {
        traceId_ = getDefaultInstance().getTraceId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string traceId = 1;</code>
       * @param value The bytes for traceId to set.
       * @return This builder for chaining.
       */
      public Builder setTraceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        traceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string serviceName = 2;</code>
       * @return The serviceName.
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceName = 2;</code>
       * @return The bytes for serviceName.
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceName = 2;</code>
       * @param value The serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serviceName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceName() {
        serviceName_ = getDefaultInstance().getServiceName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 2;</code>
       * @param value The bytes for serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serviceName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string methodName = 3;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        methodName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        methodName_ = getDefaultInstance().getMethodName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        methodName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureParamTypesIsMutable() {
        if (!paramTypes_.isModifiable()) {
          paramTypes_ = new com.google.protobuf.LazyStringArrayList(paramTypes_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @return A list containing the paramTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParamTypesList() {
        paramTypes_.makeImmutable();
        return paramTypes_;
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @return The count of paramTypes.
       */
      public int getParamTypesCount() {
        return paramTypes_.size();
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index of the element to return.
       * @return The paramTypes at the given index.
       */
      public java.lang.String getParamTypes(int index) {
        return paramTypes_.get(index);
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the paramTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParamTypesBytes(int index) {
        return paramTypes_.getByteString(index);
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index to set the value at.
       * @param value The paramTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParamTypes(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamTypesIsMutable();
        paramTypes_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param value The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param values The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParamTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramTypes_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParamTypes() {
        paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数类名
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param value The bytes of the paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> params_ = emptyList(com.google.protobuf.ByteString.class);
      private void ensureParamsIsMutable() {
        if (!params_.isModifiable()) {
          params_ = makeMutableCopy(params_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <pre>
       *bytes类型充当参数
       * </pre>
       *
       * <code>repeated bytes params = 5;</code>
       * @return A list containing the params.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getParamsList() {
        params_.makeImmutable();
        return params_;
      }
      /**
       * <pre>
       *bytes类型充当参数
       * </pre>
       *
       * <code>repeated bytes params = 5;</code>
       * @return The count of params.
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <pre>
       *bytes类型充当参数
       * </pre>
       *
       * <code>repeated bytes params = 5;</code>
       * @param index The index of the element to return.
       * @return The params at the given index.
       */
      public com.google.protobuf.ByteString getParams(int index) {
        return params_.get(index);
      }
      /**
       * <pre>
       *bytes类型充当参数
       * </pre>
       *
       * <code>repeated bytes params = 5;</code>
       * @param index The index to set the value at.
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamsIsMutable();
        params_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *bytes类型充当参数
       * </pre>
       *
       * <code>repeated bytes params = 5;</code>
       * @param value The params to add.
       * @return This builder for chaining.
       */
      public Builder addParams(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamsIsMutable();
        params_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *bytes类型充当参数
       * </pre>
       *
       * <code>repeated bytes params = 5;</code>
       * @param values The params to add.
       * @return This builder for chaining.
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, params_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *bytes类型充当参数
       * </pre>
       *
       * <code>repeated bytes params = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        params_ = emptyList(com.google.protobuf.ByteString.class);
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.liubs.shadowrpc.protocol.entity.ShadowRPCRequest)
    }

    // @@protoc_insertion_point(class_scope:com.liubs.shadowrpc.protocol.entity.ShadowRPCRequest)
    private static final com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest();
    }

    public static com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShadowRPCRequest>
        PARSER = new com.google.protobuf.AbstractParser<ShadowRPCRequest>() {
      @java.lang.Override
      public ShadowRPCRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ShadowRPCRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShadowRPCRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.liubs.shadowrpc.protocol.entity.ShadowRPCRequestProto.ShadowRPCRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022#com.liubs.shadowrpc.pro" +
      "tocol.entity\"p\n\020ShadowRPCRequest\022\017\n\007trac" +
      "eId\030\001 \001(\t\022\023\n\013serviceName\030\002 \001(\t\022\022\n\nmethod" +
      "Name\030\003 \001(\t\022\022\n\nparamTypes\030\004 \003(\t\022\016\n\006params" +
      "\030\005 \003(\014B\027B\025ShadowRPCRequestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liubs_shadowrpc_protocol_entity_ShadowRPCRequest_descriptor,
        new java.lang.String[] { "TraceId", "ServiceName", "MethodName", "ParamTypes", "Params", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
